version: '3'

services:
#  db:
#    restart: always
#    container_name: db
#    image: mysql
#    environment:
#      MYSQL_DATABASE: arattaDB
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_ROOT_HOST: toor
#
#    volumes:
#    - ./sql:/docker-entrypoint-initdb.d
##    ports:
##    - "33060:3306"
#    expose:
#      - "33060"
#
#    networks:
#        - def
  db:
    restart: always
    container_name: "postgresDb"
    image: postgres:latest
    ports:
      - 54320:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "toor"
      POSTGRES_DB: aratta
    volumes:
      - my_dbdata:/var/lib/postgresql/data

  app:
    container_name: app
    restart: always
    build:
      context: "."
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    expose:
      - "8080"
    networks:
      - def
    depends_on:
      - db


networks:
  def:
    driver: bridge

#    network_mode: 'host'
#  app:
#    container_name: app
#    restart: always
##    build: ./
#    build: .
#      context: ./
#      dockerfile: Dockerfile
#
#    expose:
#    - "8081"
#    ports:
#    - "8081:8081"
##    environment:
##    WAIT_HOSTS: mysql:3306
#    depends_on:
#    - db